function escapeAttribute(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

export function loginHtml(siteKey: string, setup = false): string {
  const turnstile = siteKey
    ? `<div class="cf-turnstile" data-sitekey="${escapeAttribute(siteKey)}" data-theme="light" data-action="turnstile-spin-v2"></div><script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>`
    : '';
  const confirm = setup
    ? '<label>Confirm password<input name="confirmPassword" type="password" autocomplete="new-password" minlength="14" maxlength="1024" required></label>'
    : '';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Private access</title><link rel="stylesheet" href="/admin/style.css"></head><body class="login-page"><main class="login-shell"><section class="login-card"><div class="brand"><span></span>Ritik<span>.us</span></div><p class="kicker">Private workspace</p><h1>${setup ? 'Create owner access.' : 'Welcome back.'}</h1><p class="muted">${setup ? 'Choose the only administrator ID and a unique 14+ character password.' : 'This area is restricted to the site owner.'}</p><form id="loginForm" data-mode="${setup ? 'setup' : 'login'}"><label>Admin ID<input name="username" autocomplete="username" minlength="3" maxlength="64" pattern="[A-Za-z0-9._-]+" required></label><label>Password<input name="password" type="password" autocomplete="${setup ? 'new-password' : 'current-password'}" minlength="14" maxlength="1024" required></label>${confirm}${turnstile}<button type="submit">${setup ? 'Create secure account' : 'Continue'} <span>→</span></button><p class="form-status" id="loginStatus" role="status"></p></form><p class="security-note">Protected by a one-time gateway, rate limits, and secure server-side sessions.</p></section></main><script src="/admin/login.js"></script></body></html>`;
}

export const LOGIN_JS = `
async function readPayload(response){const type=(response.headers.get('content-type')||'').toLowerCase();if(!type.includes('application/json'))throw new Error('The secure service was temporarily unavailable. Return home, reopen private access, and try again.');return response.json();}
function turnstileResponse(){const apiToken=window.turnstile?.getResponse?.();if(typeof apiToken==='string'&&apiToken)return apiToken;const field=document.querySelector('[name="cf-turnstile-response"]');return field&&typeof field.value==='string'?field.value:'';}
function responseError(payload,response){if(payload&&typeof payload.error==='string')return payload.error;if(payload&&typeof payload.message==='string')return payload.message;return 'Secure request failed ('+response.status+'). Return home, reopen private access, and try again.';}
const form=document.getElementById('loginForm');const status=document.getElementById('loginStatus');form.addEventListener('submit',async(e)=>{e.preventDefault();status.textContent=form.dataset.mode==='setup'?'Creating secure account…':'Checking…';const button=form.querySelector('button');button.disabled=true;const data=new FormData(form);const password=String(data.get('password')||'');const confirmPassword=String(data.get('confirmPassword')||'');if(form.dataset.mode==='setup'&&password!==confirmPassword){status.textContent='Passwords do not match.';button.disabled=false;return;}const verificationToken=turnstileResponse();if(!verificationToken){status.textContent='Human verification is still loading. Wait a moment and try again.';button.disabled=false;return;}try{const response=await fetch(form.dataset.mode==='setup'?'/api/admin/setup':'/api/admin/login',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({username:String(data.get('username')||''),password,confirmPassword,'cf-turnstile-response':verificationToken})});const payload=await readPayload(response);if(!response.ok)throw new Error(responseError(payload,response));location.replace('/admin');}catch(error){status.textContent=error instanceof Error?error.message:'Unable to continue.';window.turnstile?.reset?.();button.disabled=false;}});
`;
